# Generated by Django 2.1.12 on 2019-09-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20190903_1655"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe", old_name="ingredientes", new_name="ingredients",
        ),
    ]
